executor: KubernetesExecutor

postgresql:
  enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/rasolonjanahary/ecommerce-gitops.git
    branch: main
    subPath: dags
    depth: 1

data:
  metadataConnection:
    user: airflow
    pass: 12122005
    protocol: postgresql
    host: postgres.ecommerce.svc.cluster.local
    port: 5432
    db: airflow

webserver:
  defaultUser:
    enabled: true
    username: admin
    password: 12122005

env:
  - name: AIRFLOW_CONN_ECOMMERCE_DB
    value: postgresql://ecommerce:12122005@postgres.ecommerce.svc.cluster.local:5432/ecommerce

  - name: AIRFLOW_CONN_WAREHOUSE_DB
    value: postgresql://warehouse:12122005@postgres.ecommerce.svc.cluster.local:5432/warehouse